### ISSUE TITLE
Utility to generate boilerplate?

### ISSUE THREAD

**Issue by ivanschuetz** [cucumber-rs/cucumber#179] opened 2021-12-07 08:19 UTC
Was just wondering whether a utility to generate Rust code based on features (empty functions with macros basically) exists or has been considered? This is likely out of scope for this crate, but couldn't find infos so thought to ask anyway.

**Comment by ilslv** [comment] 2021-12-07 14:27
Duplicate of https://github.com/cucumber-rs/cucumber/issues/106

> But we can pretty easily implement custom Writer, which will output code for implementing steps:
```
[Summary]
1 feature
4 scenarios (4 skipped)
4 steps (4 skipped)

You can implement missing steps with the snippets below:

#[given(regex = r"wait 1 sec")]
#[when(regex = r"wait 1 sec")]
#[then(regex = r"wait 1 sec")]
async fn wait_1_sec(world: &mut MyWorld) {}
```

**Closed by ilslv** 2021-12-07 14:27 UTC
Labels: duplicate
