### ISSUE TITLE
`Println` doesn't work

### ISSUE THREAD

**Issue by evergreen-trading-systems** [cucumber-rs/cucumber#149] opened 2021-10-31 13:37 UTC
https://github.com/cucumber-rs/cucumber/issues/92 doesn't work using macros

```rust
#[then("verify valid response")]
async fn verify_request(world: &mut W) {
    println!("{:?}",22);
}
```

**Comment by ilslv** [comment] 2021-11-01 06:27
@evergreen-trading-systems please provide version you are using, because I can't reproduce it on latest `v0.10`

Modified readme example:
```rust
use std::{convert::Infallible, time::Duration};

use async_trait::async_trait;
use cucumber::{given, then, when, WorldInit};
use tokio::time::sleep;

#[derive(Debug, WorldInit)]
struct World {
    user: Option<String>,
    capacity: usize,
}

#[async_trait(?Send)]
impl cucumber::World for World {
    type Error = Infallible;

    async fn new() -> Result<Self, Self::Error> {
        Ok(Self {
            user: None,
            capacity: 0,
        })
    }
}

#[given(regex = r"^(\S+) is hungry$")]
async fn someone_is_hungry(w: &mut World, user: String) {
    sleep(Duration::from_secs(2)).await;

    // Here we print
    println!("Someone is hungry");

    w.user = Some(user);
}

#[when(regex = r"^(?:he|she|they) eats? (\d+) cucumbers?$")]
async fn eat_cucumbers(w: &mut World, count: usize) {
    sleep(Duration::from_secs(2)).await;

    w.capacity += count;

    assert!(w.capacity < 4, "{} exploded!", w.user.as_ref().unwrap());
}

#[then(regex = r"^(?:he|she|they) (?:is|are) full$")]
async fn is_full(w: &mut World) {
    sleep(Duration::from_secs(2)).await;

    assert_eq!(w.capacity, 3, "{} isn't full!", w.user.as_ref().unwrap());
}

#[tokio::main]
async fn main() {
    World::run("tests/features/readme").await;
}
```

To see output you should run `cargo test --test readme -- --color=never --concurrency=1`. `--color=never` is used because by default `writer::Basic` pretty-prints by overriding previous statements, so user output can interfere. `--concurrency=1` should be used to avoid multiple concurrent `Scenario`s  outputting at the same time.

[![asciicast](https://asciinema.org/a/yNLYRruVKbFxk5xZfKBAJpg7T.svg)](https://asciinema.org/a/yNLYRruVKbFxk5xZfKBAJpg7T)

Mentioning all that it's not recommended to use `println!` macro. Rather you should use `assert!` macro with meaningful error message. In that case you can run pretty-printed and concurrently letting the library to output panic message at the right time. 

```rust 
#[given(regex = r"^(\S+) is hungry$")]
async fn someone_is_hungry(w: &mut World, user: String) {
    sleep(Duration::from_secs(2)).await;

    assert!(false, "Someone is hungry");

    w.user = Some(user);
}
``` 

[![asciicast](https://asciinema.org/a/ItBD7jnZqrnUatcfDZaYZ9poV.svg)](https://asciinema.org/a/ItBD7jnZqrnUatcfDZaYZ9poV)

**Comment by tyranron** [comment] 2021-11-05 17:26
Closing this, @evergreen-trading-systems feel free to reopen if you need further assistance.

**Closed by tyranron** 2021-11-05 17:26 UTC
Labels: question
